quarkus:
  hibernate-orm:
    database:
      generation: drop-and-create
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:staging;DB_CLOSE_DELAY=-1
greeting:
  message: "Hi, I'm from staging :)"